### ISSUE TITLE
[Holonix] Upload binaries to Cachix

### ISSUE THREAD

**Issue by jost-s** [holochain/holonix#4]
AC:
- [x] all binaries [built as Holonix packages](https://github.com/holochain/holonix/blob/main/flake.nix#L120) are pushed to Cachix
- [x] add this step to the existing build workflow
- [x] ideally there's a test step to make sure binaries are pulled from cache and not built locally

**Comment by ThetaSinner** [comment]
it's a separate workflow for trigger complexity reasons, but there's now a workflow to publish binaries to cachix -> https://github.com/holochain/holonix/blob/main/.github/workflows/holonix-cache.yaml

Just having some trouble with intel mac... because of course we are :)

**Comment by ThetaSinner** [comment]
Cache verification is done here -> https://github.com/holochain/holonix/blob/main/.github/workflows/holonix-cache.yaml#L90
